kind: pipeline
type: docker
name: default

clone:
  git:
    image: plugins/git
    recursive: true

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive

- name: build
  image: lagerdata/devenv-cortexm
  commands:
  - lager exec cmake-build

- name: flash-moose
  image: lagerdata/devenv-cortexm
  commands:
  - lager connect --device nrf52 --interface ftdi --transport swd --force --gateway majestic-moose
  - lager testrun --serial-device /dev/ttyACM0 --hexfile _build/test/test_suite_1/blue42_test1.hex  --gateway majestic-moose

- name: flash-jaguar
  image: lagerdata/devenv-cortexm
  commands:
  - lager connect --device nrf52 --interface ftdi --transport swd --force --gateway jovial-jaguar
  - lager testrun --serial-device /dev/ttyACM0 --hexfile _build/test/test_suite_1/blue42_test1.hex  --gateway jovial-jaguar

- name: notify
  image: lagerdata/devenv-cortexm
  depends_on:
  - flash-moose
  - flash-jaguar
  commands:
  - echo "Done"