kind: pipeline
type: docker
name: default

clone:
  git:
    image: plugins/git
    recursive: true

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive

- name: build
  image: lagerdata/devenv-cortexm
  commands:
  - lager exec cmake-build

- name: flash
  image: lagerdata/devenv-cortexm
  commands:
  - lager set default gateway majestic-moose
  - lager connect --device nrf52 --interface ftdi --transport swd --force
  - lager testrun --serial-device /dev/ttyACM0 --hexfile third_party/nRF5_SDK_17.0.0_9d13099/components/softdevice/s140/hex/s140_nrf52_7.0.1_softdevice.hex --hexfile _build/test/test_suite_1/blue42_test1.hex --test-runner unity