name: Run tests
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build test1
        uses: docker://lagerdata/devenv-cortexm@sha256:60a0deea0522d8976e5adba70811d57cde6ea2caa2fc395e099201aa3dd6a295
        with:
          entrypoint: lager
          args: exec cmake-test1

      - name: Build mpudrv
        uses: docker://lagerdata/devenv-cortexm@sha256:60a0deea0522d8976e5adba70811d57cde6ea2caa2fc395e099201aa3dd6a295
        with:
          entrypoint: lager
          args: exec cmake-mpudrv

      - name: Connect moose
        uses: docker://lagerdata/lager-cli:v0.1.31
        env:
          LAGER_SECRET_TOKEN: ${{ secrets.LAGER_SECRET_TOKEN }}
        with:
          entrypoint: lager
          args: connect --device nrf52 --interface ftdi --transport swd --force --gateway majestic-moose

      - name: Testrun moose
        uses: docker://lagerdata/lager-cli:v0.1.31
        env:
          LAGER_SECRET_TOKEN: ${{ secrets.LAGER_SECRET_TOKEN }}
        with:
          entrypoint: lager
          args: testrun --serial-device /dev/ttyACM0 --hexfile _build/test/test_suite_mpu9250_drv/blue42_test_mpu9250_drv.hex --hexfile third_party/nRF5_SDK_17.0.0_9d13099/components/softdevice/s140/hex/s140_nrf52_7.0.1_softdevice.hex --gateway majestic-moose
